{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MMBTabBarController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/mmbtabbarcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/mmbtabbarcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding","doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling","doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject","doc:\/\/cathaybk.DDTSample\/s7CVarArgP","doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP","doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP","doc:\/\/cathaybk.DDTSample\/SQ","doc:\/\/cathaybk.DDTSample\/SH","doc:\/\/cathaybk.DDTSample\/s8SendableP","doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions","doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring","doc:\/\/cathaybk.DDTSample\/objc(pl)UITabBarDelegate","doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MMBTabBarController"}],"title":"MMBTabBarController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DDTSample@objc(cs)MMBTabBarController","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"MMBTabBarController"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample"]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample/MMBTabBarController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/ddtsample\/mmbtabbarcontroller\/initwithnibname:bundle:"},"doc://cathaybk.DDTSample/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment"},"doc://cathaybk.DDTSample/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cathaybk.DDTSample\/s7CVarArgP"},"doc://cathaybk.DDTSample/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting"},"doc://cathaybk.DDTSample/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions"},"doc://cathaybk.DDTSample/documentation/DDTSample/MMBTabBarController":{"role":"symbol","title":"MMBTabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MMBTabBarController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MMBTabBarController"}],"url":"\/documentation\/ddtsample\/mmbtabbarcontroller"},"doc://cathaybk.DDTSample/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding"},"doc://cathaybk.DDTSample/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/objc(pl)UITabBarDelegate":{"type":"unresolvable","title":"UIKit.UITabBarDelegate","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UITabBarDelegate"},"doc://cathaybk.DDTSample/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP"},"doc://cathaybk.DDTSample/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer"},"doc://cathaybk.DDTSample/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling"},"doc://cathaybk.DDTSample/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment"},"doc://cathaybk.DDTSample/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP"},"doc://cathaybk.DDTSample/documentation/DDTSample/MMBTabBarController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/ddtsample\/mmbtabbarcontroller\/viewdidload()"},"doc://cathaybk.DDTSample/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer"},"doc://cathaybk.DDTSample/documentation/DDTSample/MMBTabBarController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ddtsample\/mmbtabbarcontroller\/initwithcoder:"},"doc://cathaybk.DDTSample/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cathaybk.DDTSample\/SH"},"doc://cathaybk.DDTSample/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cathaybk.DDTSample\/SQ"},"doc://cathaybk.DDTSample/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"},"doc://cathaybk.DDTSample/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cathaybk.DDTSample/objc(cs)UITabBarController":{"type":"unresolvable","title":"UITabBarController","identifier":"doc:\/\/cathaybk.DDTSample\/objc(cs)UITabBarController"},"doc://cathaybk.DDTSample/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject"},"doc://cathaybk.DDTSample/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cathaybk.DDTSample\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MMBTabBarController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MMBTabBarController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MMBTabBarController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/initWithCoder:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/initWithNibName:bundle:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UITabBarController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MMBTabBarController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITabBarController","preciseIdentifier":"c:objc(cs)UITabBarController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController\/title","value":"MMBTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController\/fragments","value":[{"kind":"identifier","text":"MMBTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}