{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoneyViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/moneyviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/moneyviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding","doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling","doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject","doc:\/\/cathaybk.DDTSample\/s7CVarArgP","doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP","doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP","doc:\/\/cathaybk.DDTSample\/SQ","doc:\/\/cathaybk.DDTSample\/SH","doc:\/\/cathaybk.DDTSample\/s8SendableP","doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions","doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring","doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/money"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/buttonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/printMtehodButtonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoneyViewController"}],"title":"MoneyViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DDTSample@objc(cs)MoneyViewController","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"MoneyViewController"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample"]]},"references":{"doc://cathaybk.DDTSample/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject"},"doc://cathaybk.DDTSample/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling"},"doc://cathaybk.DDTSample/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment"},"doc://cathaybk.DDTSample/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment"},"doc://cathaybk.DDTSample/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP"},"doc://cathaybk.DDTSample/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cathaybk.DDTSample\/SH"},"doc://cathaybk.DDTSample/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cathaybk.DDTSample\/SQ"},"doc://cathaybk.DDTSample/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding"},"doc://cathaybk.DDTSample/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/printMtehodButtonAction(_:)":{"role":"symbol","title":"printMtehodButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printMtehodButtonAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/printMtehodButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"printMtehodButtonAction:"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller\/printmtehodbuttonaction(_:)"},"doc://cathaybk.DDTSample/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController":{"role":"symbol","title":"MoneyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoneyViewController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MoneyViewController"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller"},"doc://cathaybk.DDTSample/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller\/viewdidload()"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller\/initwithcoder:"},"doc://cathaybk.DDTSample/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cathaybk.DDTSample\/s7CVarArgP"},"doc://cathaybk.DDTSample/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring"},"doc://cathaybk.DDTSample/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer"},"doc://cathaybk.DDTSample/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/money":{"role":"symbol","title":"money","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"money"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/money","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample\/moneyviewcontroller\/money"},"doc://cathaybk.DDTSample/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cathaybk.DDTSample\/s8SendableP"},"doc://cathaybk.DDTSample/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP"},"doc://cathaybk.DDTSample/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller\/initwithnibname:bundle:"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController/buttonAction(_:)":{"role":"symbol","title":"buttonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/buttonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buttonAction:"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller\/buttonaction(_:)"},"doc://cathaybk.DDTSample/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MoneyViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MoneyViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MoneyViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/buttonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/initWithCoder:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/initWithNibName:bundle:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/printMtehodButtonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoneyViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1printMtehodButtonAction(_:)\/title","value":"printMtehodButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1printMtehodButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printMtehodButtonAction:"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController\/title","value":"MoneyViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController\/fragments","value":[{"kind":"identifier","text":"MoneyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1buttonAction(_:)\/title","value":"buttonAction:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController~1buttonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buttonAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}