{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBOutlet"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/friendtableviewcell\/namelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/friendtableviewcell\/namelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/nameLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"nameLabel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DDTSample@objc(cs)FriendTableViewCell(py)nameLabel","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"nameLabel"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell"]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell":{"role":"symbol","title":"FriendTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendTableViewCell"}],"url":"\/documentation\/ddtsample\/friendtableviewcell"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/nameLabel":{"role":"symbol","title":"nameLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/nameLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nameLabel"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/namelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nameLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nameLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"nameLabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/title","value":"FriendTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/fragments","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1nameLabel\/title","value":"nameLabel"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1nameLabel\/fragments","value":[{"kind":"identifier","text":"nameLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}