{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connectionOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/scenedelegate\/scene(_:willconnectto:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/scenedelegate\/scene(_:willconnectto:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/scene(_:willConnectTo:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISceneDelegate.scene(_:willConnectTo:options:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"title":"scene(_:willConnectTo:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DDTSample@objc(cs)SceneDelegate(im)scene:willConnectToSession:options:","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate"]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate":{"role":"symbol","title":"SceneDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneDelegate"}],"url":"\/documentation\/ddtsample\/scenedelegate"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate/scene(_:willConnectTo:options:)":{"role":"symbol","title":"scene(_:willConnectTo:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/scene(_:willConnectTo:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"url":"\/documentation\/ddtsample\/scenedelegate\/scene(_:willconnectto:options:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scene:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scene"},{"kind":"text","text":" "},{"kind":"identifier","text":"willConnectToSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISceneConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"connectionOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/title","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1scene(_:willConnectTo:options:)\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1scene(_:willConnectTo:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}