{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/scenedelegate\/window"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/scenedelegate\/window"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/window","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIWindowSceneDelegate.window"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"title":"window","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DDTSample@objc(cs)SceneDelegate(py)window","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"window"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate"]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate/window":{"role":"symbol","title":"window","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"window"}],"url":"\/documentation\/ddtsample\/scenedelegate\/window"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate":{"role":"symbol","title":"SceneDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneDelegate"}],"url":"\/documentation\/ddtsample\/scenedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"window"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"window"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" * "},{"kind":"identifier","text":"window"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1window\/title","value":"window"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/title","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}