{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/friendtableviewcell\/awakefromnib()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/friendtableviewcell\/awakefromnib()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/awakeFromNib()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"title":"awakeFromNib()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DDTSample@objc(cs)FriendTableViewCell(im)awakeFromNib","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell"]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell":{"role":"symbol","title":"FriendTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendTableViewCell"}],"url":"\/documentation\/ddtsample\/friendtableviewcell"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/awakefromnib()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"awakeFromNib"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/title","value":"FriendTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/fragments","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}