{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"image.png"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/AppDelegate","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/ViewController"]}],"kind":"symbol","metadata":{"roleHeading":"Application","externalID":"DDTSample","title":"DDTSample","symbolKind":"module","role":"collection","modules":[{"name":"DDTSample"}]},"hierarchy":{"paths":[[]]},"references":{"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell":{"role":"symbol","title":"FriendTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendTableViewCell"}],"url":"\/documentation\/ddtsample\/friendtableviewcell"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyView":{"role":"symbol","title":"MoneyView","fragments":[{"kind":"identifier","text":"MoneyView"}],"abstract":[{"type":"text","text":"測試標題"}],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyView","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample\/moneyview"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"image.png":{"alt":"圖片","type":"image","identifier":"image.png","variants":[{"url":"\/images\/image.png","traits":["1x","light"]}]},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate":{"role":"symbol","title":"SceneDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneDelegate"}],"url":"\/documentation\/ddtsample\/scenedelegate"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController":{"role":"symbol","title":"KOKOViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOKOViewController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KOKOViewController"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller"},"doc://cathaybk.DDTSample/documentation/DDTSample/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/ddtsample\/appdelegate"},"doc://cathaybk.DDTSample/documentation/DDTSample/ViewController":{"role":"symbol","title":"ViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/ViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewController"}],"url":"\/documentation\/ddtsample\/viewcontroller"},"doc://cathaybk.DDTSample/documentation/DDTSample/MMBTabBarController":{"role":"symbol","title":"MMBTabBarController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MMBTabBarController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MMBTabBarController"}],"url":"\/documentation\/ddtsample\/mmbtabbarcontroller"},"doc://cathaybk.DDTSample/documentation/DDTSample/MoneyViewController":{"role":"symbol","title":"MoneyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoneyViewController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MoneyViewController"}],"url":"\/documentation\/ddtsample\/moneyviewcontroller"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendViewController":{"role":"symbol","title":"FriendViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendViewController"}],"abstract":[{"type":"text","text":"好友頁面"}],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendViewController"}],"url":"\/documentation\/ddtsample\/friendviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/AppDelegate","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MMBTabBarController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyView","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/MoneyViewController","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/ViewController"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/title","value":"FriendTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/fragments","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/title","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController\/title","value":"KOKOViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController\/fragments","value":[{"kind":"identifier","text":"KOKOViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1ViewController\/title","value":"ViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1ViewController\/fragments","value":[{"kind":"identifier","text":"ViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController\/title","value":"MMBTabBarController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MMBTabBarController\/fragments","value":[{"kind":"identifier","text":"MMBTabBarController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController\/title","value":"MoneyViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1MoneyViewController\/fragments","value":[{"kind":"identifier","text":"MoneyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendViewController\/title","value":"FriendViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendViewController\/fragments","value":[{"kind":"identifier","text":"FriendViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}