{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/friendtableviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/friendtableviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding","doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject","doc:\/\/cathaybk.DDTSample\/objc(pl)CALayerDelegate","doc:\/\/cathaybk.DDTSample\/s7CVarArgP","doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP","doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP","doc:\/\/cathaybk.DDTSample\/SQ","doc:\/\/cathaybk.DDTSample\/SH","doc:\/\/cathaybk.DDTSample\/s8SendableP","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAccessibilityIdentification","doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearance","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UICoordinateSpace","doc:\/\/cathaybk.DDTSample\/objc(pl)UIDynamicItem","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusItem","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusItemContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/cathaybk.DDTSample\/objc(pl)UILargeContentViewerItem","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions","doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/nameLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/awakeFromNib()","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/setSelected(_:animated:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"title":"FriendTableViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DDTSample@objc(cs)FriendTableViewCell","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"FriendTableViewCell"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample"]]},"references":{"doc://cathaybk.DDTSample/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP"},"doc://cathaybk.DDTSample/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cathaybk.DDTSample\/SH"},"doc://cathaybk.DDTSample/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cathaybk.DDTSample\/s7CVarArgP"},"doc://cathaybk.DDTSample/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearance"},"doc://cathaybk.DDTSample/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAccessibilityIdentification"},"doc://cathaybk.DDTSample/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIGestureRecognizerDelegate"},"doc://cathaybk.DDTSample/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/initwithstyle:reuseidentifier:"},"doc://cathaybk.DDTSample/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)CALayerDelegate"},"doc://cathaybk.DDTSample/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UICoordinateSpace"},"doc://cathaybk.DDTSample/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://cathaybk.DDTSample/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusItem"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/awakefromnib()"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell":{"role":"symbol","title":"FriendTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FriendTableViewCell"}],"url":"\/documentation\/ddtsample\/friendtableviewcell"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/initwithcoder:"},"doc://cathaybk.DDTSample/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions"},"doc://cathaybk.DDTSample/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cathaybk.DDTSample\/SQ"},"doc://cathaybk.DDTSample/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/cathaybk.DDTSample\/objc(cs)UITableViewCell"},"doc://cathaybk.DDTSample/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting"},"doc://cathaybk.DDTSample/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cathaybk.DDTSample/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/setSelected(_:animated:)":{"role":"symbol","title":"setSelected(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/setSelected(_:animated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelected:animated:"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/setselected(_:animated:)"},"doc://cathaybk.DDTSample/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusItemContainer"},"doc://cathaybk.DDTSample/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UILargeContentViewerItem"},"doc://cathaybk.DDTSample/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer"},"doc://cathaybk.DDTSample/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP"},"doc://cathaybk.DDTSample/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject"},"doc://cathaybk.DDTSample/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding"},"doc://cathaybk.DDTSample/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"},"doc://cathaybk.DDTSample/documentation/DDTSample/FriendTableViewCell/nameLabel":{"role":"symbol","title":"nameLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/nameLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nameLabel"}],"url":"\/documentation\/ddtsample\/friendtableviewcell\/namelabel"},"doc://cathaybk.DDTSample/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIDynamicItem"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cathaybk.DDTSample\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FriendTableViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/nameLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/awakeFromNib()","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/initWithCoder:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/initWithStyle:reuseIdentifier:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/FriendTableViewCell\/setSelected(_:animated:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FriendTableViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/title","value":"FriendTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell\/fragments","value":[{"kind":"identifier","text":"FriendTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1setSelected(_:animated:)\/title","value":"setSelected:animated:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1setSelected(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelected:animated:"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1nameLabel\/title","value":"nameLabel"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1FriendTableViewCell~1nameLabel\/fragments","value":[{"kind":"identifier","text":"nameLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}