{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOKOViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/kokoviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/kokoviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding","doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling","doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject","doc:\/\/cathaybk.DDTSample\/s7CVarArgP","doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP","doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP","doc:\/\/cathaybk.DDTSample\/SQ","doc:\/\/cathaybk.DDTSample\/SH","doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer","doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions","doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring","doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment","doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/money"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/printMtehodButtonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOKOViewController"}],"title":"KOKOViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DDTSample@objc(cs)KOKOViewController","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"KOKOViewController"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample"]]},"references":{"doc://cathaybk.DDTSample/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cathaybk.DDTSample\/s7CVarArgP"},"doc://cathaybk.DDTSample/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIContentContainer"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController":{"role":"symbol","title":"KOKOViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOKOViewController"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KOKOViewController"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller\/viewdidload()"},"doc://cathaybk.DDTSample/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller\/initwithnibname:bundle:"},"doc://cathaybk.DDTSample/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cathaybk.DDTSample\/SQ"},"doc://cathaybk.DDTSample/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIFocusEnvironment"},"doc://cathaybk.DDTSample/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIAppearanceContainer"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController/printMtehodButtonAction(_:)":{"role":"symbol","title":"printMtehodButtonAction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"printMtehodButtonAction"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/printMtehodButtonAction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"printMtehodButtonAction:"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller\/printmtehodbuttonaction(_:)"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController/money":{"role":"symbol","title":"money","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"money"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/money","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample\/kokoviewcontroller\/money"},"doc://cathaybk.DDTSample/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP"},"doc://cathaybk.DDTSample/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cathaybk.DDTSample/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject"},"doc://cathaybk.DDTSample/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSCoding"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP"},"doc://cathaybk.DDTSample/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cathaybk.DDTSample\/SH"},"doc://cathaybk.DDTSample/documentation/DDTSample/KOKOViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/ddtsample\/kokoviewcontroller\/initwithcoder:"},"doc://cathaybk.DDTSample/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions"},"doc://cathaybk.DDTSample/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"},"doc://cathaybk.DDTSample/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UITraitEnvironment"},"doc://cathaybk.DDTSample/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting"},"doc://cathaybk.DDTSample/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIStateRestoring"},"doc://cathaybk.DDTSample/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSExtensionRequestHandling"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"KOKOViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"KOKOViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"KOKOViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/initWithCoder:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/initWithNibName:bundle:","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/printMtehodButtonAction(_:)","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/KOKOViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"KOKOViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController\/title","value":"KOKOViewController"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController\/fragments","value":[{"kind":"identifier","text":"KOKOViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController~1printMtehodButtonAction(_:)\/title","value":"printMtehodButtonAction:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1KOKOViewController~1printMtehodButtonAction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"printMtehodButtonAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}