{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ddtsample\/scenedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ddtsample\/scenedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject","doc:\/\/cathaybk.DDTSample\/s7CVarArgP","doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP","doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP","doc:\/\/cathaybk.DDTSample\/SQ","doc:\/\/cathaybk.DDTSample\/SH","doc:\/\/cathaybk.DDTSample\/s8SendableP","doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions","doc:\/\/cathaybk.DDTSample\/objc(pl)UISceneDelegate","doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring","doc:\/\/cathaybk.DDTSample\/objc(pl)UIWindowSceneDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/scene(_:willConnectTo:options:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"title":"SceneDelegate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DDTSample@objc(cs)SceneDelegate","modules":[{"name":"DDTSample"}],"navigatorTitle":[{"kind":"identifier","text":"SceneDelegate"}]},"hierarchy":{"paths":[["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample"]]},"references":{"doc://cathaybk.DDTSample/objc(pl)UISceneDelegate":{"type":"unresolvable","title":"UIKit.UISceneDelegate","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UISceneDelegate"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate/scene(_:willConnectTo:options:)":{"role":"symbol","title":"scene(_:willConnectTo:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/scene(_:willConnectTo:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"url":"\/documentation\/ddtsample\/scenedelegate\/scene(_:willconnectto:options:)"},"doc://cathaybk.DDTSample/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/cathaybk.DDTSample\/s8SendableP"},"doc://cathaybk.DDTSample/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://cathaybk.DDTSample/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/cathaybk.DDTSample\/SQ"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/ddtsample\/scenedelegate\/init"},"doc://cathaybk.DDTSample/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIUserActivityRestoring"},"doc://cathaybk.DDTSample/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/cathaybk.DDTSample\/s7CVarArgP"},"doc://cathaybk.DDTSample/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/cathaybk.DDTSample\/SH"},"doc://cathaybk.DDTSample/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIResponderStandardEditActions"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate":{"role":"symbol","title":"SceneDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SceneDelegate"}],"url":"\/documentation\/ddtsample\/scenedelegate"},"doc://cathaybk.DDTSample/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIPasteConfigurationSupporting"},"doc://cathaybk.DDTSample/documentation/DDTSample":{"role":"collection","title":"DDTSample","abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample","kind":"symbol","type":"topic","url":"\/documentation\/ddtsample"},"doc://cathaybk.DDTSample/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)NSObject"},"doc://cathaybk.DDTSample/objc(cs)UIResponder":{"type":"unresolvable","title":"UIResponder","identifier":"doc:\/\/cathaybk.DDTSample\/objc(cs)UIResponder"},"doc://cathaybk.DDTSample/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s23CustomStringConvertibleP"},"doc://cathaybk.DDTSample/documentation/DDTSample/SceneDelegate/window":{"role":"symbol","title":"window","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"window"}],"url":"\/documentation\/ddtsample\/scenedelegate\/window"},"doc://cathaybk.DDTSample/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/cathaybk.DDTSample\/s28CustomDebugStringConvertibleP"},"doc://cathaybk.DDTSample/objc(pl)UIWindowSceneDelegate":{"type":"unresolvable","title":"UIWindowSceneDelegate","identifier":"doc:\/\/cathaybk.DDTSample\/objc(pl)UIWindowSceneDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SceneDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/window"]},{"title":"Instance Methods","identifiers":["doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/init","doc:\/\/cathaybk.DDTSample\/documentation\/DDTSample\/SceneDelegate\/scene(_:willConnectTo:options:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(cs)UIResponder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/cathaybk.DDTSample\/objc(pl)UIWindowSceneDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SceneDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIResponder","preciseIdentifier":"c:objc(cs)UIResponder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1scene(_:willConnectTo:options:)\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1scene(_:willConnectTo:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/title","value":"SceneDelegate"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate\/fragments","value":[{"kind":"identifier","text":"SceneDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1window\/title","value":"window"},{"op":"replace","path":"\/references\/doc:~1~1cathaybk.DDTSample~1documentation~1DDTSample~1SceneDelegate~1window\/fragments","value":[{"kind":"identifier","text":"window"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}